# Generated by Django 5.0.6 on 2025-05-20 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(max_length=100)),
                ('ItemDescription', models.CharField(max_length=255)),
                ('ItemSize', models.CharField(max_length=100)),
                ('Rate', models.CharField(max_length=300)),
                ('Disc', models.CharField(max_length=300)),
                ('Qty', models.CharField(max_length=300)),
                ('Unit', models.CharField(max_length=300)),
                ('Particular', models.CharField(max_length=255)),
                ('MakeMillName', models.CharField(max_length=255)),
                ('DeliveryDate', models.DateField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='All_Masters.item')),
            ],
        ),
    ]
