# Generated by Django 5.0.6 on 2025-05-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Masters', '0002_itemtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtransaction',
            name='PartCode',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
