# Generated by Django 5.0.6 on 2025-06-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Masters', '0004_itemtransaction2'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='OPRate',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='PieceRate',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='WipRate',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='WipWt',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
