# Generated by Django 5.0.6 on 2025-06-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Masters', '0005_bomitem_oprate_bomitem_piecerate_bomitem_wiprate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='ProdQty',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
