# Generated by Django 5.0.6 on 2025-06-03 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Masters', '0006_bomitem_prodqty'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom_itempartmaster',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='bompartmaster_entries', to='All_Masters.itemtable'),
            preserve_default=False,
        ),
    ]
