# Generated by Django 5.0.6 on 2025-06-03 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Masters', '0009_alter_bom_itempartmaster_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom_itempartmaster',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bompartmaster_entries', to='All_Masters.itemtable'),
        ),
    ]
