# Generated by Django 5.0.6 on 2025-06-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Masters', '0010_alter_bom_itempartmaster_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='Operation',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
