# Generated by Django 5.0.6 on 2025-06-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Masters', '0011_bomitem_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='BomPartDesc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
