# Generated by Django 5.2.5 on 2025-09-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Masters', '0012_bomitem_bompartdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomitem',
            name='BomPartCode',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
