# Generated by Django 5.2.8 on 2026-02-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Masters', '0013_alter_bomitem_bompartcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Name',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
