# Generated by Django 5.2.8 on 2026-03-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Masters', '0014_alter_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle_time_master_model',
            name='part_code',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='cycle_time_master_model',
            name='part_desc',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='cycle_time_master_model',
            name='part_no',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
