# Generated by Django 5.2.8 on 2026-03-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Masters', '0015_cycle_time_master_model_part_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomitem',
            name='QC',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
