# Generated by Django 5.2.8 on 2026-05-20 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Masters', '0016_alter_bomitem_qc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_item', models.CharField(blank=True, max_length=5000, null=True)),
                ('tool_life', models.CharField(blank=True, max_length=200, null=True)),
                ('no_of_resharpening', models.CharField(blank=True, max_length=200, null=True)),
                ('total', models.CharField(blank=True, max_length=200, null=True)),
                ('bom_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='All_Masters.bomitem')),
            ],
        ),
    ]
