# Generated by Django 5.2.8 on 2026-05-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendingBillGrnlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_no', models.CharField(blank=True, max_length=200, null=True)),
                ('grn_date', models.DateField(blank=True, null=True)),
                ('challan_no', models.CharField(blank=True, max_length=200, null=True)),
                ('challan_date', models.DateField(blank=True, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=200, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=500, null=True)),
                ('po_no', models.CharField(blank=True, max_length=200, null=True)),
                ('total', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.CharField(blank=True, max_length=200, null=True)),
                ('select', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
