# Generated by Django 5.2.8 on 2026-05-13 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(blank=True, max_length=200, null=True)),
                ('bill_type', models.CharField(blank=True, max_length=200, null=True)),
                ('series_no', models.CharField(blank=True, max_length=200, null=True)),
                ('no', models.CharField(blank=True, max_length=200, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=500, null=True)),
                ('item_name', models.CharField(blank=True, max_length=300, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('fwd_charges', models.CharField(blank=True, max_length=200, null=True)),
                ('transport_charged', models.CharField(blank=True, max_length=200, null=True)),
                ('insurence', models.CharField(blank=True, max_length=200, null=True)),
                ('installation_charges', models.CharField(blank=True, max_length=200, null=True)),
                ('other_charges', models.CharField(blank=True, max_length=200, null=True)),
                ('challan_date', models.DateField(blank=True, null=True)),
                ('payment_days_terms', models.CharField(blank=True, max_length=200, null=True)),
                ('tds', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_total', models.CharField(blank=True, max_length=200, null=True)),
                ('challan_no', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('other_amt', models.CharField(blank=True, max_length=200, null=True)),
                ('assable_value', models.CharField(blank=True, max_length=200, null=True)),
                ('posting_date', models.DateField(blank=True, null=True)),
                ('round_of_amt', models.CharField(blank=True, max_length=200, null=True)),
                ('net_total', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillRegisterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_no', models.CharField(blank=True, max_length=200, null=True)),
                ('chall_no', models.CharField(blank=True, max_length=200, null=True)),
                ('po_no', models.CharField(blank=True, max_length=200, null=True)),
                ('item_code', models.CharField(blank=True, max_length=200, null=True)),
                ('item_no', models.CharField(blank=True, max_length=200, null=True)),
                ('item_description', models.CharField(blank=True, max_length=200, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=200, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('grn_qty', models.CharField(blank=True, max_length=200, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cgst_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sgst_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('igst_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('glid', models.CharField(blank=True, max_length=200, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('bill_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Account.billregister')),
            ],
        ),
    ]
