# Generated by Django 6.0.5 on 2026-05-15 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_billregister_billregisteritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobworkBillRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_no', models.CharField(blank=True, max_length=200, null=True)),
                ('bill_no', models.CharField(blank=True, max_length=200, null=True)),
                ('supplier', models.CharField(blank=True, max_length=500, null=True)),
                ('inv_challan_no', models.CharField(blank=True, max_length=200, null=True)),
                ('inv_challan_date', models.DateField(blank=True, null=True)),
                ('payment_terms_days', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('posting_date', models.DateField(blank=True, null=True)),
                ('assable_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('tds', models.CharField(blank=True, max_length=200, null=True)),
                ('tcs', models.CharField(blank=True, max_length=200, null=True)),
                ('round_of_amt', models.CharField(blank=True, max_length=200, null=True)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('pack_forward_charge', models.CharField(blank=True, max_length=200, null=True)),
                ('transport_charge', models.CharField(blank=True, max_length=200, null=True)),
                ('insurance', models.CharField(blank=True, max_length=200, null=True)),
                ('installation_charge', models.CharField(blank=True, max_length=200, null=True)),
                ('ohter_amount', models.CharField(blank=True, max_length=200, null=True)),
                ('add_item', models.CharField(blank=True, max_length=200, null=True)),
                ('total_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sub_total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('dis_total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('basic_total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cgst_total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sgst_total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('igst_total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('other_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('bill_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('tds_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('tcs_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('final_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobworkBillRegisterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_no', models.CharField(blank=True, max_length=200, null=True)),
                ('chal_no', models.CharField(blank=True, max_length=200, null=True)),
                ('po_no', models.CharField(blank=True, max_length=200, null=True)),
                ('item_no', models.CharField(blank=True, max_length=200, null=True)),
                ('item_code', models.CharField(blank=True, max_length=200, null=True)),
                ('item_description', models.CharField(blank=True, max_length=200, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=200, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('grn_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('challan_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('dis', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('dis_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cgst_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sgst_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('igst_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('glid', models.CharField(blank=True, max_length=200, null=True)),
                ('tds', models.BooleanField(blank=True, default=False, null=True)),
                ('bill_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Account.jobworkbillregister')),
            ],
        ),
    ]
