# Generated by Django 5.2.8 on 2026-05-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_jobworkbillregister_jobworkbillregisteritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralLedgerMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gl_code', models.CharField(blank=True, max_length=200, null=True)),
                ('gl_description', models.CharField(blank=True, max_length=500, null=True)),
                ('gl_category', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
