# Generated by Django 5.0.6 on 2025-04-04 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewGrnList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PoNo', models.CharField(blank=True, max_length=255, null=True)),
                ('Date', models.CharField(blank=True, max_length=255, null=True)),
                ('ItemNoCode', models.CharField(blank=True, max_length=255, null=True)),
                ('Description', models.CharField(blank=True, max_length=255, null=True)),
                ('Rate', models.CharField(blank=True, max_length=255, null=True)),
                ('PoQty', models.CharField(blank=True, max_length=255, null=True)),
                ('BalQty', models.CharField(blank=True, max_length=255, null=True)),
                ('ChalQty', models.CharField(blank=True, max_length=255, null=True)),
                ('GrnQty', models.CharField(blank=True, max_length=255, null=True)),
                ('ShortExcessQty', models.CharField(blank=True, max_length=255, null=True)),
                ('UnitCode', models.CharField(blank=True, max_length=255, null=True)),
                ('Total', models.CharField(blank=True, max_length=255, null=True)),
                ('HeatNo', models.CharField(blank=True, max_length=255, null=True)),
                ('MfgDate', models.CharField(blank=True, max_length=255, null=True)),
                ('New_MRN_Detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NewGrnList', to='Store.grngenraldetail')),
            ],
        ),
    ]
