# Generated by Django 5.0.6 on 2025-04-21 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_newgrnlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plant', models.CharField(blank=True, max_length=255, null=True)),
                ('Series', models.CharField(blank=True, max_length=255, null=True)),
                ('IndentNo', models.CharField(blank=True, max_length=255, null=True)),
                ('Date', models.CharField(blank=True, max_length=255, null=True)),
                ('Time', models.CharField(blank=True, max_length=255, null=True)),
                ('Category', models.BooleanField(blank=True, max_length=255, null=True)),
                ('CPCCode', models.CharField(blank=True, max_length=255, null=True)),
                ('WorkOrder', models.CharField(blank=True, max_length=255, null=True)),
                ('Remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SecondNew_Indent',
        ),
        migrations.RenameField(
            model_name='new_indent',
            old_name='Available',
            new_name='ItemNoCpcCode',
        ),
        migrations.RenameField(
            model_name='new_indent',
            old_name='Department',
            new_name='MachineAndDepartment',
        ),
        migrations.RemoveField(
            model_name='new_indent',
            name='Machine',
        ),
        migrations.RemoveField(
            model_name='new_indent',
            name='SelectItem',
        ),
        migrations.AddField(
            model_name='new_indent',
            name='New_Indent_Detail',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='New_Indent', to='Store.indent'),
            preserve_default=False,
        ),
    ]
