# Generated by Django 5.0.6 on 2025-04-22 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_indent_delete_secondnew_indent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plant', models.CharField(blank=True, max_length=255, null=True)),
                ('ChallanNo', models.CharField(blank=True, max_length=255, null=True)),
                ('Series', models.CharField(blank=True, max_length=255, null=True)),
                ('Type', models.CharField(blank=True, max_length=255, null=True)),
                ('Item', models.CharField(blank=True, max_length=255, null=True)),
                ('ItemDescription', models.CharField(blank=True, max_length=255, null=True)),
                ('Available', models.CharField(blank=True, max_length=255, null=True)),
                ('Stock', models.CharField(blank=True, max_length=255, null=True)),
                ('Machine', models.CharField(blank=True, max_length=255, null=True)),
                ('StoreName', models.CharField(blank=True, max_length=255, null=True)),
                ('Qty', models.CharField(blank=True, max_length=255, null=True)),
                ('Unit', models.CharField(blank=True, max_length=255, null=True)),
                ('Remark', models.CharField(blank=True, max_length=255, null=True)),
                ('MrnNo', models.CharField(blank=True, max_length=255, null=True)),
                ('Employee', models.CharField(blank=True, max_length=255, null=True)),
                ('Dept', models.CharField(blank=True, max_length=255, null=True)),
                ('MaterialIssueDate', models.CharField(blank=True, max_length=255, null=True)),
                ('MaterialIssueTime', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialChallanTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemDescription', models.CharField(blank=True, max_length=255, null=True)),
                ('Stock', models.CharField(blank=True, max_length=255, null=True)),
                ('Qty', models.CharField(blank=True, max_length=255, null=True)),
                ('Unit', models.CharField(blank=True, max_length=255, null=True)),
                ('Machine', models.CharField(blank=True, max_length=255, null=True)),
                ('NatureOfWork', models.CharField(blank=True, max_length=255, null=True)),
                ('MrnNo', models.CharField(blank=True, max_length=255, null=True)),
                ('CoilNo', models.CharField(blank=True, max_length=255, null=True)),
                ('Employee', models.CharField(blank=True, max_length=255, null=True)),
                ('Dept', models.CharField(blank=True, max_length=255, null=True)),
                ('MaterialChallanDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MaterialChallanTable', to='Store.materialchallan')),
            ],
        ),
    ]
