# Generated by Django 5.0.6 on 2025-04-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_materialchallan_materialchallantable'),
    ]

    operations = [
        migrations.AddField(
            model_name='indent',
            name='Auth',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='indent',
            name='Category',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
