# Generated by Django 5.0.6 on 2025-04-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_indent_auth_alter_indent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialchallan',
            name='Contractor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
