# Generated by Django 5.0.6 on 2025-04-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_materialchallan_contractor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_indent',
            name='New_Indent_Detail',
        ),
        migrations.DeleteModel(
            name='Indent',
        ),
        migrations.DeleteModel(
            name='New_Indent',
        ),
    ]
