# Generated by Django 5.0.6 on 2025-04-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_remove_new_indent_new_indent_detail_delete_indent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGroup2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_group_name', models.CharField(max_length=100)),
                ('prefix', models.CharField(blank=True, max_length=10, null=True)),
                ('group_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MainGroup2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10)),
                ('subgroup_code', models.CharField(max_length=300)),
                ('subgroup_name', models.CharField(max_length=100)),
                ('inventory', models.CharField(max_length=10)),
            ],
        ),
    ]
