# Generated by Django 5.0.6 on 2025-04-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_itemgroup2_maingroup2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemgroup2',
            name='group_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='itemgroup2',
            name='prefix',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='maingroup2',
            name='prefix',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='maingroup2',
            name='subgroup_code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='maingroup2',
            name='subgroup_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
