# Generated by Django 5.0.6 on 2025-05-05 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_alter_itemgroup2_group_name_alter_itemgroup2_prefix_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemGroup2',
        ),
        migrations.DeleteModel(
            name='MainGroup2',
        ),
    ]
