# Generated by Django 5.0.6 on 2025-05-30 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0011_generaldetails_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewDCgrn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plant', models.CharField(blank=True, max_length=255, null=True)),
                ('DCGRNno', models.CharField(blank=True, max_length=255, null=True)),
                ('Type', models.CharField(blank=True, max_length=255, null=True)),
                ('GateEntryNo', models.CharField(blank=True, max_length=255, null=True)),
                ('Series', models.CharField(blank=True, max_length=255, null=True)),
                ('SuppCust', models.CharField(blank=True, max_length=255, null=True)),
                ('SelectDC', models.CharField(blank=True, max_length=255, null=True)),
                ('Item', models.CharField(blank=True, max_length=255, null=True)),
                ('GRNno', models.CharField(blank=True, max_length=255, null=True)),
                ('GRNDate', models.CharField(blank=True, max_length=255, null=True)),
                ('GRNTime', models.CharField(blank=True, max_length=255, null=True)),
                ('ChallanNo', models.CharField(blank=True, max_length=255, null=True)),
                ('ChallanDate', models.CharField(blank=True, max_length=255, null=True)),
                ('VehicleNo', models.CharField(blank=True, max_length=255, null=True)),
                ('LRno', models.CharField(blank=True, max_length=255, null=True)),
                ('Trasporter', models.CharField(blank=True, max_length=255, null=True)),
                ('PreparedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('CheckedByApprovedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('Remark', models.CharField(blank=True, max_length=255, null=True)),
                ('DeliveryInTime', models.CharField(blank=True, max_length=255, null=True)),
                ('QCcheck', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewDCgrnTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DCno', models.CharField(blank=True, max_length=255, null=True)),
                ('Date', models.CharField(blank=True, max_length=255, null=True)),
                ('ItemCode', models.CharField(blank=True, max_length=255, null=True)),
                ('Description', models.CharField(blank=True, max_length=255, null=True)),
                ('Rate', models.CharField(blank=True, max_length=255, null=True)),
                ('DCqty', models.CharField(blank=True, max_length=255, null=True)),
                ('Balqty', models.CharField(blank=True, max_length=255, null=True)),
                ('Chalqty', models.CharField(blank=True, max_length=255, null=True)),
                ('GRNqty', models.CharField(blank=True, max_length=255, null=True)),
                ('ShortExcessqty', models.CharField(blank=True, max_length=255, null=True)),
                ('UnitCode', models.CharField(blank=True, max_length=255, null=True)),
                ('Total', models.CharField(blank=True, max_length=255, null=True)),
                ('HeatCode', models.CharField(blank=True, max_length=255, null=True)),
                ('Remark', models.CharField(blank=True, max_length=255, null=True)),
                ('NewDCgrnDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NewDCgrnTable', to='Store.newdcgrn')),
            ],
        ),
    ]
