# Generated by Django 5.0.6 on 2025-05-30 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0012_newdcgrn_newdcgrntable'),
    ]

    operations = [
        migrations.CreateModel(
            name='InwardChallan2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Routing', models.CharField(blank=True, max_length=255, null=True)),
                ('Plant', models.CharField(blank=True, max_length=255, null=True)),
                ('Series', models.CharField(blank=True, max_length=255, null=True)),
                ('InwardChallanNo', models.CharField(blank=True, max_length=255, null=True)),
                ('SupplierName', models.CharField(blank=True, max_length=255, null=True)),
                ('OutwardChallan', models.CharField(blank=True, max_length=255, null=True)),
                ('ItemName', models.CharField(blank=True, max_length=255, null=True)),
                ('InwardF4No', models.CharField(blank=True, max_length=255, null=True)),
                ('InwardDate', models.CharField(blank=True, max_length=255, null=True)),
                ('InwardTime', models.CharField(blank=True, max_length=255, null=True)),
                ('ChallanNo', models.CharField(blank=True, max_length=255, null=True)),
                ('ChallanDate', models.CharField(blank=True, max_length=255, null=True)),
                ('GateEntryNo', models.CharField(blank=True, max_length=255, null=True)),
                ('InvoiceNo', models.CharField(blank=True, max_length=255, null=True)),
                ('InvoiceDate', models.CharField(blank=True, max_length=255, null=True)),
                ('EwayBillQty', models.CharField(blank=True, max_length=255, null=True)),
                ('EwayBillNo', models.CharField(blank=True, max_length=255, null=True)),
                ('VehicleNo', models.CharField(blank=True, max_length=255, null=True)),
                ('LrNo', models.CharField(blank=True, max_length=255, null=True)),
                ('Transporter', models.CharField(blank=True, max_length=255, null=True)),
                ('PreparedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('CheckedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('TcNo', models.CharField(blank=True, max_length=255, null=True)),
                ('TcDate', models.CharField(blank=True, max_length=255, null=True)),
                ('Remark', models.CharField(blank=True, max_length=255, null=True)),
                ('DeliveryInTime', models.CharField(blank=True, max_length=255, null=True)),
                ('TotalItem', models.CharField(blank=True, max_length=255, null=True)),
                ('TotalQtyNo', models.CharField(blank=True, max_length=255, null=True)),
                ('TotalQtyKg', models.CharField(blank=True, max_length=255, null=True)),
                ('Store', models.CharField(blank=True, max_length=255, null=True)),
                ('TOC', models.CharField(blank=True, max_length=255, null=True)),
                ('PackFwrdCharges', models.CharField(blank=True, max_length=255, null=True)),
                ('TransportCharges', models.CharField(blank=True, max_length=255, null=True)),
                ('Insurance', models.CharField(blank=True, max_length=255, null=True)),
                ('InstallationCharge', models.CharField(blank=True, max_length=255, null=True)),
                ('OtherCharges', models.CharField(blank=True, max_length=255, null=True)),
                ('CGST', models.CharField(blank=True, max_length=255, null=True)),
                ('SGST', models.CharField(blank=True, max_length=255, null=True)),
                ('IGST', models.CharField(blank=True, max_length=255, null=True)),
                ('TCS', models.CharField(blank=True, max_length=255, null=True)),
                ('GRTotal', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InwardChallanGSTDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemCode', models.CharField(blank=True, max_length=255, null=True)),
                ('SACCode', models.CharField(blank=True, max_length=255, null=True)),
                ('PORate', models.CharField(blank=True, max_length=255, null=True)),
                ('RateType', models.CharField(blank=True, max_length=255, null=True)),
                ('Qty', models.CharField(blank=True, max_length=255, null=True)),
                ('Discount', models.CharField(blank=True, max_length=255, null=True)),
                ('PackAmt', models.CharField(blank=True, max_length=255, null=True)),
                ('TransAmt', models.CharField(blank=True, max_length=255, null=True)),
                ('AssValue', models.CharField(blank=True, max_length=255, null=True)),
                ('CGST', models.CharField(blank=True, max_length=255, null=True)),
                ('SGST', models.CharField(blank=True, max_length=255, null=True)),
                ('IGST', models.CharField(blank=True, max_length=255, null=True)),
                ('InwardChallanDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InwardChallanGSTDetails', to='Store.inwardchallan2')),
            ],
        ),
        migrations.CreateModel(
            name='InwardChallanTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OutNo', models.CharField(blank=True, max_length=255, null=True)),
                ('OutDate', models.CharField(blank=True, max_length=255, null=True)),
                ('ItemDescription', models.CharField(blank=True, max_length=255, null=True)),
                ('OutIn', models.CharField(blank=True, max_length=255, null=True)),
                ('Unit', models.CharField(blank=True, max_length=255, null=True)),
                ('OutQty', models.CharField(blank=True, max_length=255, null=True)),
                ('BalQty', models.CharField(blank=True, max_length=255, null=True)),
                ('ChallanQty', models.CharField(blank=True, max_length=255, null=True)),
                ('InQtyNOS', models.CharField(blank=True, max_length=255, null=True)),
                ('InQtyKg', models.CharField(blank=True, max_length=255, null=True)),
                ('JwRate', models.CharField(blank=True, max_length=255, null=True)),
                ('InwardChallanDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InwardChallanTable', to='Store.inwardchallan2')),
            ],
        ),
    ]
