# Generated by Django 5.2.3 on 2025-07-03 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0013_inwardchallan2_inwardchallangstdetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobworkInwardChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plant', models.CharField(blank=True, max_length=255, null=True)),
                ('Series', models.CharField(blank=True, max_length=255, null=True)),
                ('NO', models.CharField(blank=True, max_length=255, null=True)),
                ('GateEntryNo', models.CharField(blank=True, max_length=255, null=True)),
                ('Customer', models.CharField(blank=True, max_length=255, null=True)),
                ('SelectItem', models.CharField(blank=True, max_length=255, null=True)),
                ('ItemCode', models.CharField(blank=True, max_length=255, null=True)),
                ('FGPartCode', models.CharField(blank=True, max_length=255, null=True)),
                ('ChallanQty', models.CharField(blank=True, max_length=255, null=True)),
                ('GRNQty', models.CharField(blank=True, max_length=255, null=True)),
                ('MaterialRate', models.CharField(blank=True, max_length=255, null=True)),
                ('HeatNo', models.CharField(blank=True, max_length=255, null=True)),
                ('CustHeatNo', models.CharField(blank=True, max_length=255, null=True)),
                ('RMSpecification', models.CharField(blank=True, max_length=255, null=True)),
                ('PaticularNatureOfProcess', models.CharField(blank=True, max_length=255, null=True)),
                ('InwardF4No', models.CharField(blank=True, max_length=255, null=True)),
                ('InwardDate', models.CharField(blank=True, max_length=255, null=True)),
                ('InwardTime', models.CharField(blank=True, max_length=255, null=True)),
                ('ChallanNo', models.CharField(blank=True, max_length=255, null=True)),
                ('ChallanDate', models.CharField(blank=True, max_length=255, null=True)),
                ('SubVendor', models.CharField(blank=True, max_length=255, null=True)),
                ('DCNo', models.CharField(blank=True, max_length=255, null=True)),
                ('DCDate', models.CharField(blank=True, max_length=255, null=True)),
                ('WayBillQty', models.CharField(blank=True, max_length=255, null=True)),
                ('WayBillNo', models.CharField(blank=True, max_length=255, null=True)),
                ('VehicleNo', models.CharField(blank=True, max_length=255, null=True)),
                ('LrNo', models.CharField(blank=True, max_length=255, null=True)),
                ('Transporter', models.CharField(blank=True, max_length=255, null=True)),
                ('PrepartedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('CheckedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('VehicleInTime', models.CharField(blank=True, max_length=255, null=True)),
                ('TCNo', models.CharField(blank=True, max_length=255, null=True)),
                ('TCDate', models.CharField(blank=True, max_length=255, null=True)),
                ('Remark', models.CharField(blank=True, max_length=255, null=True)),
                ('DevileryInTime', models.CharField(blank=True, max_length=255, null=True)),
                ('ClearingStatus', models.CharField(blank=True, max_length=255, null=True)),
                ('VehicleOutTime', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobworkInwardChallanTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemCode', models.CharField(blank=True, max_length=255, null=True)),
                ('Operation', models.CharField(blank=True, max_length=255, null=True)),
                ('ChallanQty', models.CharField(blank=True, max_length=255, null=True)),
                ('GRNQty', models.CharField(blank=True, max_length=255, null=True)),
                ('MaterialRate', models.CharField(blank=True, max_length=255, null=True)),
                ('HeatNo', models.CharField(blank=True, max_length=255, null=True)),
                ('CustHeatNo', models.CharField(blank=True, max_length=255, null=True)),
                ('ParticularNatureOfProcess', models.CharField(blank=True, max_length=255, null=True)),
                ('JobworkInwardChallanDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JobworkInwardChallanTable', to='Store.jobworkinwardchallan')),
            ],
        ),
    ]
