# Generated by Django 5.2.3 on 2025-07-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0015_newmrn_approve_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmrn',
            name='Approve_status',
            field=models.CharField(choices=[('Approved', 'approved'), ('Pending', 'pending'), ('Rejected', 'rejected')], default='pending'),
        ),
    ]
