# Generated by Django 5.2.3 on 2025-07-16 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0005_remove_onwardchallanitem_grn_detail'),
        ('Store', '0016_alter_newmrn_approve_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='grngenraldetail',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grndetails', to='Sales.onwardchallanitem'),
        ),
    ]
