# Generated by Django 5.2.3 on 2025-07-21 06:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0017_grngenraldetail_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FGMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trn_no', models.CharField(blank=True, max_length=300, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('fg_item_code', models.CharField(max_length=100)),
                ('fg_item_name', models.CharField(max_length=255)),
                ('fg_item_description', models.TextField(blank=True)),
                ('operation', models.CharField(blank=True, max_length=100)),
                ('ok_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rework_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reject_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('heat_code', models.CharField(blank=True, max_length=300)),
                ('stock_view', models.CharField(default='All', max_length=300)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fg_movement',
                'ordering': ['-created_at'],
            },
        ),
    ]
