# Generated by Django 5.2.3 on 2025-07-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0018_fgmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaldetails',
            name='po_reference',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
