# Generated by Django 4.2.20 on 2025-07-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0019_generaldetails_po_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmrn',
            name='Approve_status',
            field=models.CharField(choices=[('Approved', 'approved'), ('Pending', 'pending'), ('Rejected', 'rejected')], default='pending', max_length=255),
        ),
    ]
