# Generated by Django 5.2.5 on 2025-09-12 05:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0020_alter_newmrn_approve_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grngenraldetail',
            name='GrnTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
