# Generated by Django 5.2.5 on 2025-09-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0021_alter_grngenraldetail_grntime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grngenraldetail',
            name='GrnTime',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
