# Generated by Django 5.2.5 on 2025-10-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0022_alter_grngenraldetail_grntime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newgrnlist',
            name='GrnQty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
