# Generated by Django 5.2.8 on 2026-03-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0024_materialchallantable_heatno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobworkinwardchallan',
            name='FGPartCode',
        ),
        migrations.AddField(
            model_name='jobworkinwardchallantable',
            name='FGPartCode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
