# Generated by Django 5.2.8 on 2026-03-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0025_remove_jobworkinwardchallan_fgpartcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwardchallantable',
            name='heat_no',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
