# Generated by Django 6.0.5 on 2026-06-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0026_inwardchallantable_heat_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='grngst',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
