# Generated by Django 6.0.5 on 2026-07-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0027_grngst_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaldetails',
            name='EWayBillDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
