# Generated by Django 6.0.5 on 2026-07-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0028_alter_generaldetails_ewaybilldate'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwardchallantable',
            name='opno',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
