# Generated by Django 6.0.5 on 2026-08-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0029_inwardchallantable_opno'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningStockFG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(blank=True, max_length=300, null=True)),
                ('tm_no', models.CharField(blank=True, max_length=300, null=True)),
                ('tm_date', models.DateField(blank=True, null=True)),
                ('item_code', models.CharField(blank=True, max_length=500, null=True)),
                ('part_code', models.CharField(blank=True, max_length=500, null=True)),
                ('heat_no', models.CharField(blank=True, max_length=500, null=True)),
                ('new_heat_no', models.CharField(blank=True, max_length=500, null=True)),
                ('ok_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('rework_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('reject_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('remark_note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
