# Generated by Django 6.0.5 on 2026-10-09 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0030_openingstockfg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverychallan',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='deliverychallan',
            name='HSNCode',
        ),
        migrations.RemoveField(
            model_name='deliverychallan',
            name='ItemCode',
        ),
        migrations.RemoveField(
            model_name='deliverychallan',
            name='Purpose',
        ),
        migrations.RemoveField(
            model_name='deliverychallan',
            name='Qty',
        ),
        migrations.RemoveField(
            model_name='deliverychallan',
            name='Rate',
        ),
        migrations.RemoveField(
            model_name='deliverychallan',
            name='SelectItem',
        ),
        migrations.RemoveField(
            model_name='deliverychallan',
            name='Store',
        ),
        migrations.RemoveField(
            model_name='deliverychallan',
            name='Unit',
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='add_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='assessable_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='cgst_amt',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='challan_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='challan_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='contractor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='dc_series',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='dc_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='deparment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='e_way_bill_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='igst_amt',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='inventory',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='lr_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='plant',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='po_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='po_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='ref_person_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='sgst_amt',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='supplier',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='transport',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='vehical_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DeliveryChallanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(blank=True, max_length=100, null=True)),
                ('item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('item_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=100, null=True)),
                ('purpose', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('delivery_challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Store.deliverychallan')),
            ],
        ),
    ]
