from django.contrib import admin
# Register your models here.
from .models import *

admin.site.register(PoInfo)
admin.site.register(JwPoInfo)
admin.site.register(JwItemDetail)
admin.site.register(JwShipAdd)
admin.site.register(Quote_Comparison_Statement)
admin.site.register(CodeGenerator)
admin.site.register(PurchaseOrder)
admin.site.register(PurchaseNewIndent)
admin.site.register(MYDetail)
admin.site.register(ItemDetail)
admin.site.register(GSTDetails)
admin.site.register(ItemDetailsOther)
admin.site.register(ScheduleLine)
admin.site.register(ShipToAdd)
admin.site.register(PurchasePO)
admin.site.register(Item)
admin.site.register(Indent)
admin.site.register(New_Indent)
admin.site.register(ItemTransaction2)
admin.site.register(NewJobWorkItemDetails)
admin.site.register(NewJobWorkGstDetails)
admin.site.register(NewJobWorkScheduleLine)
admin.site.register(NewJobWorkShipToAdd)
admin.site.register(NewJobWorkPoInfo)
admin.site.register(QuotationComparison)
admin.site.register(RFQ)