# Generated by Django 5.0.6 on 2025-05-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail2',
            name='Plant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
