# Generated by Django 4.2.20 on 2025-08-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0002_productdetail2_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionentry',
            name='raw_material',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
