# Generated by Django 5.0.6 on 2025-05-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0002_indent_new_indent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetail',
            name='DeliveryDt',
            field=models.DateField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='Disc',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='Item',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='ItemDescription',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='ItemSize',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='Mill_Name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='Particular',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='Qty',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='Rate',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='Unit',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
