# Generated by Django 5.0.6 on 2025-05-08 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0004_purchasepo_codeno_purchasepo_plant_purchasepo_series_and_more'),
        ('Settings', '0002_remove_financialyear_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasepo',
            name='financial_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Settings.financialyear'),
        ),
    ]
