# Generated by Django 5.0.6 on 2025-05-08 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0005_purchasepo_financial_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasepo',
            name='financial_year',
        ),
    ]
