# Generated by Django 5.0.6 on 2025-05-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0006_remove_purchasepo_financial_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gstdetails',
            name='GR_Total',
        ),
        migrations.RemoveField(
            model_name='gstdetails',
            name='TOC_AssableValue',
        ),
        migrations.RemoveField(
            model_name='gstdetails',
            name='TOC_CESS',
        ),
        migrations.RemoveField(
            model_name='gstdetails',
            name='TOC_CGST',
        ),
        migrations.RemoveField(
            model_name='gstdetails',
            name='TOC_IGST',
        ),
        migrations.RemoveField(
            model_name='gstdetails',
            name='TOC_InstallationCharges',
        ),
        migrations.RemoveField(
            model_name='gstdetails',
            name='TOC_Insurance',
        ),
        migrations.RemoveField(
            model_name='gstdetails',
            name='TOC_PackCharges',
        ),
        migrations.RemoveField(
            model_name='gstdetails',
            name='TOC_SGST',
        ),
        migrations.RemoveField(
            model_name='gstdetails',
            name='TOC_TDS',
        ),
        migrations.RemoveField(
            model_name='gstdetails',
            name='TOC_TransportCost',
        ),
        migrations.RemoveField(
            model_name='gstdetails',
            name='TOC_VAT',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='POType',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='Plant',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='Series',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='Supplier',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='purchasepo',
            name='GR_Total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchasepo',
            name='TOC_AssableValue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchasepo',
            name='TOC_CESS',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchasepo',
            name='TOC_CGST',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchasepo',
            name='TOC_IGST',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchasepo',
            name='TOC_InstallationCharges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchasepo',
            name='TOC_Insurance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchasepo',
            name='TOC_PackCharges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchasepo',
            name='TOC_SGST',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchasepo',
            name='TOC_TDS',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchasepo',
            name='TOC_TransportCost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchasepo',
            name='TOC_VAT',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
