# Generated by Django 5.0.6 on 2025-05-22 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0008_newjobworkgstdetails_newjobworkitemdetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newjobworkpoinfo',
            name='Item_Details_Other',
        ),
    ]
