# Generated by Django 5.2.3 on 2025-07-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0011_newjobworkpoinfo_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasepo',
            name='Approved_Status',
            field=models.CharField(choices=[('Approved', 'approved'), ('Pending', 'pending'), ('Rejected', 'reject')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchasepo',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
