# Generated by Django 5.2.3 on 2025-07-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0012_purchasepo_approved_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_RFQ', models.CharField(blank=True, max_length=300, null=True)),
                ('item', models.CharField(blank=True, max_length=300, null=True)),
                ('make', models.CharField(blank=True, max_length=300, null=True)),
                ('minimum_purchase_quantity', models.IntegerField(blank=True, null=True)),
                ('other_charges', models.IntegerField(blank=True, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=300, null=True)),
                ('uom', models.CharField(blank=True, max_length=300, null=True)),
                ('tax_applicable', models.CharField(blank=True, max_length=300, null=True)),
                ('remark_details', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_quote_no', models.CharField(blank=True, max_length=300, null=True)),
                ('basic_rate', models.IntegerField(blank=True, null=True)),
                ('delivery_mode', models.CharField(blank=True, max_length=300, null=True)),
                ('quote_date', models.DateField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('delivery_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq_type', models.CharField(choices=[('single', 'For Single'), ('enquiry', 'Against Enquiry')], max_length=10)),
                ('rfq_no', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('item', models.CharField(choices=[('new', 'New'), ('existing', 'Existing')], max_length=10)),
                ('item_no', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_location', models.TextField()),
                ('payment_term', models.TextField()),
                ('delivery_schedule', models.TextField()),
                ('to_date', models.DateField()),
                ('indent_no', models.CharField(blank=True, max_length=300, null=True)),
                ('unit', models.CharField(choices=[('PCS', 'PCS'), ('KGS', 'KGS'), ('Box', 'Box'), ('LTR', 'LTR'), ('NOS', 'NOS'), ('SQFT', 'SQFT'), ('MTR', 'MTR'), ('FOOT', 'FOOT'), ('SQMTR', 'SQMTR'), ('PAIR', 'PAIR'), ('BAG', 'BAG'), ('PACKET', 'PACKET'), ('RIM', 'RIM'), ('SET', 'SET'), ('MT', 'MT'), ('PER DAY', 'PER DAY'), ('DOZEN', 'DOZEN'), ('JOB', 'JOB'), ('SQUINCH', 'SQUINCH')], max_length=300)),
                ('quality_terms', models.TextField()),
                ('remark_details', models.TextField(blank=True, null=True)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('project_name', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
