# Generated by Django 5.2.3 on 2025-07-21 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0013_quotationcomparison_rfq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='purchase_order',
        ),
        migrations.AddField(
            model_name='newjobworkitemdetails',
            name='purchase_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Purchase.purchasepo'),
        ),
    ]
