# Generated by Django 5.2.5 on 2025-09-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0014_remove_item_purchase_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newjobworkitemdetails',
            name='Itemtype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
