# Generated by Django 5.2.5 on 2025-09-25 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0015_newjobworkitemdetails_itemtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newjobworkitemdetails',
            old_name='ItemDescription',
            new_name='item_description',
        ),
        migrations.RenameField(
            model_name='newjobworkitemdetails',
            old_name='ItemName',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='newjobworkitemdetails',
            old_name='Itemtype',
            new_name='item_type',
        ),
    ]
