# Generated by Django 5.2.5 on 2025-09-26 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0016_rename_itemdescription_newjobworkitemdetails_item_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newjobworkitemdetails',
            old_name='item_description',
            new_name='ItemDescription',
        ),
        migrations.RenameField(
            model_name='newjobworkitemdetails',
            old_name='item_name',
            new_name='ItemName',
        ),
    ]
