# Generated by Django 6.0.5 on 2026-06-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0017_rename_item_description_newjobworkitemdetails_itemdescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepo',
            name='field',
            field=models.CharField(choices=[('RM', 'RM'), ('CONSUMABLE', 'Consumable'), ('SERVICE', 'Service'), ('ASSET', 'Asset'), ('IMPORT', 'Import')], max_length=300),
        ),
    ]
