# Generated by Django 6.0.5 on 2026-06-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0018_alter_purchasepo_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepo',
            name='Approved_Status',
            field=models.CharField(choices=[('Approved', 'approved'), ('Pending', 'pending'), ('Rejected', 'rejected')], default='Pending', max_length=10),
        ),
    ]
