from django.contrib import admin
from .models import *
admin.site.register(TaxDetails)
admin.site.register(TaxCode)
admin.site.register(ItemMaster)
admin.site.register(Supplier_Customer)
admin.site.register(Buyer_Contact)
admin.site.register(Bank_Details)
admin.site.register(Cut_Wise)
admin.site.register(Type_Model)
admin.site.register(City_Model)
admin.site.register(ItemTransaction)
admin.site.register(ItemTable)
admin.site.register(Item_Master_Data2_Model)
admin.site.register(Technical_Specification_Model)
admin.site.register(NPD_Model)
admin.site.register(MainGroup2)
admin.site.register(ItemGroup2)
admin.site.register(MainGroup_Model)
admin.site.register(TDC_Model)
admin.site.register(MetalType_Model)
admin.site.register(Item_Group_Item_Master_Model)
admin.site.register(Item_Cross_Model)
admin.site.register(Work_Center_Model)
admin.site.register(Cycle_Time_Master_Model)
admin.site.register(Shift_Master_Model)
admin.site.register(Add_New_Operator_Model)
admin.site.register(Contractor_Api_Model)
admin.site.register(Unit_Conversion_Model)
admin.site.register(Contractor_Master_Model)
admin.site.register(Add_Price_List_Model)
admin.site.register(Price_List_Entry_Model)
admin.site.register(Operation_Master_Model)
admin.site.register(Std_Routing_Model)
admin.site.register(Item)
admin.site.register(BOMItem)
admin.site.register(BOM_ItemPartMaster)
admin.site.register(ItemTransaction2)


