from .views import *
from .views import ExcelFileUploadView, ExcelFileDownloadView
from .views import export_items_to_excel
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views
from .views import ItemReportAPIView,ItemDuplicateSearchAPIView,CustomerSupplierDuplicateSearchAPIView

router = DefaultRouter()
router.register(r'tools', ToolViewSet)
router.register(r'parts', PartViewSet, basename='part')
router.register(r'SupplierData', SupplierViewSet, basename='Supplierdata')
router.register(r'item-table', ItemTableViewSet, basename='item-table')
router.register(r'maingroup', MainGroupViewSet2)
router.register(r'itemgroup', ItemGroupViewSet2)
router.register(r'itemtable', ItemTableViewSet2)



urlpatterns = [
    path('api/', include(router.urls)),
    path('GST_Master/', GSTMasterListCreate.as_view(), name='GST_Master-retrieve-list-create'),
    path('GST_Master/<int:pk>/', GSTMasterRetrieveUpdateDestroy.as_view(), name='GST_Master-retrieve-update-destroy'),
    path('Tax_Code/', TaxCodeListCreate.as_view(), name='Tax_Code-list-create'),
    path('Tax_Code/<int:pk>/', TaxCodeRetrieveUpdateDestroy.as_view(), name='Tax_Code-retrieve-update-destroy'),
    path('Cut_Wise/', Cust_WiseListCreate.as_view(), name='Cut_Wise-list-create'),
    path('Cut_Wise/<int:pk>/', Cust_WiseRetrieveUpdateDestroy.as_view(), name='Cut_Wise-retrieve-update-destroy'),
    path('upload/', ExcelFileUploadView.as_view(), name='upload_excel_file'),
    path('download/<int:pk>/', ExcelFileDownloadView.as_view(), name='download_excel_file'),
    path('Supplier_Customer/', Supplier_CustomerListCreate.as_view(), name='Supplier_Customer-list-create'),
    path('Supplier_Customer/<int:pk>/', Supplier_CustomerRetrieveUpdateDestroy.as_view(), name='Supplier_Customer-retrieve-update-destroy'),
    path('Buyer_Contact/', Buyer_ListCreate.as_view(), name='Buyer_Contact-list-create'),
    path('Buyer_Contact/<int:pk>/', Buyer_RetrieveUpdateDestroy.as_view(), name='Buyer_Contact-retrieve-update-destroy'),
    path('Bank_Details/', Bank_ListCreate.as_view(), name='Bank_Details-list-create'),
    path('Bank_Details/<int:pk>/', Bank_RetrieveUpdateDestroy.as_view(), name='Bank_Details-retrieve-update-destroy'),
    path('Type/', Type_ListCreate.as_view(), name='Type_Details-list-create'),
    path('Type/<int:pk>/', Type_RetrieveUpdateDestroy.as_view(), name='Type_Details-retrieve-update-destroy'),
    path('Region/', Region_ListCreate.as_view(), name='Region_Details-list-create'),
    path('Region/<int:pk>/', Region_RetrieveUpdateDestroy.as_view(), name='Region_Details-retrieve-update-destroy'),
    path('states-uts/', StateUTListView.as_view(), name='state-ut-list'),
    path('StateCode/', StateCode_ListCreate.as_view(), name='StateCode_list-create'),
    path('StateCode/<int:pk>/', StateCode_RetrieveUpdateDestroy.as_view(), name='StateCode_retrieve-update-destroy'),
    path('Payment_Term/', Payment_Term_ListCreate.as_view(), name='Payment_Term_list-create'),
    path('Payment_Term/<int:pk>/', Payment_Term_RetrieveUpdateDestroy.as_view(), name='Payment_Term_retrieve-update-destroy'),
    path('Country/', Country_ListCreate.as_view(), name='Country_list-create'),
    path('Country/<int:pk>/', Country_RetrieveUpdateDestroy.as_view(), name='Country_retrieve-update-destroy'),
    path('SupplierCountry/', CountryListView.as_view(), name='SupplierCountry-list'),
    path('Currency/', Currency_ListCreate.as_view(), name='Currency_list-create'),
    path('Currency/<int:pk>/', Currency_RetrieveUpdateDestroy.as_view(), name='Currency_retrieve-update-destroy'),
    path('currency-codes/', CurrencyCodeListView.as_view(), name='currency-code-list'),
    path('City/', City_ListCreate.as_view(), name='City_list-create'),
    path('City/<int:pk>/', City_RetrieveUpdateDestroy.as_view(), name='City_retrieve-update-destroy'),
    path('Sector/', Sector_ListCreate.as_view(), name='Sector_list-create'),
    path('Sector/<int:pk>/', Sector_RetrieveUpdateDestroy.as_view(), name='Sector_retrieve-update-destroy'),
    path('Group/',Group_ListCreate.as_view(), name='Group_list-create'),
    path('Group/<int:pk>/', Group_RetrieveUpdateDestroy.as_view(), name='Group_retrieve-update-destroy'),
    path('QMSC_Code/', QMSC_Code_ListCreate.as_view(), name='QMSC_Code_list-create'),
    path('QMSC_Code/<int:pk>/', QMSC_Code_RetrieveUpdateDestroy.as_view(), name='QMSC_Code_retrieve-update-destroy'),
    path('Supplier_List/', Supplier_List_ListCreate.as_view(), name='Supplier_List_list-create'),
    path('Item_Cross/', Item_Cross_Reference_ListCreate.as_view(), name='Item_Cross_list-create'),
    path('Item_Cross/<int:pk>/', Item_Cross_Reference_RetrieveUpdateDestroy.as_view(), name='Item_Cross_retrieve-update-destroy'),
    path('Supplier_Item/', Supplier_Item_Reference_ListCreate.as_view(), name='Supplier_Item_list-create'),
    path('Supplier_Item/<int:pk>/', Supplier_Item_RetrieveUpdateDestroy.as_view(), name='Supplier_Item_retrieve-update-destroy'), 
    path('Item_VA_Rate/', Item_VA_Rate_ListCreate.as_view(), name='Item_VA_Rate_list-create'),
    path('Item_VA_Rate/<int:pk>/', Item_VA_Rate_RetrieveUpdateDestroy.as_view(), name='Item_VA_Rate_retrieve-update-destroy'),
    path('Work_Center/', Work_Center_ListCreate.as_view(), name='Work_Center_list-create'),
    path('Work_Center/<int:pk>/', Work_Center_RetrieveUpdateDestroy.as_view(), name='Work_Center_retrieve-update-destroy'),
    path('Machine_Group_Work_Center/', Machine_Group_Work_Center_ListCreate.as_view(), name='WorkCenterTypeGroup_list-create'),
    path('Machine_Group_Work_Center/<int:pk>/', Machine_Group_Work_Center_RetrieveUpdateDestroy.as_view(), name='WorkCenterTypeGroup_retrieve-update-destroy'),
    path('WorkCenterTypeGroup/', WorkCenterTypeGroup_ListCreate.as_view(), name='WorkCenterTypeGroup_list-create'),
    path('WorkCenterTypeGroup/<int:pk>/', WorkCenterTypeGroup_RetrieveUpdateDestroy.as_view(), name='WorkCenterTypeGroup_retrieve-update-destroy'),
    path('Cycle_Time_Master/', Cycle_Time_Master_ListCreate.as_view(), name='WorkCenterTypeGroup_list-create'),
    path('Cycle_Time_Master/<int:pk>/', Cycle_Time_Master_RetrieveUpdateDestroy.as_view(), name='WorkCenterTypeGroup_retrieve-update-destroy'),
    path('Shift_Master/', Shift_Master_ListCreate.as_view(), name='WorkCenterTypeGroup_list-create'),
    path('Shift_Master/<int:pk>/', Shift_Master_RetrieveUpdateDestroy.as_view(), name='WorkCenterTypeGroup_retrieve-update-destroy'),
    path('Add_New_Operator/', Add_New_Operator_ListCreate.as_view(), name='Add_New_OperatorTypeGroup_list-create'),
    path('Add_New_Operator/<int:pk>/', Add_New_Operator_RetrieveUpdateDestroy.as_view(), name='Add_New_Operator_retrieve-update-destroy'), 
    path('Department_Maste/', Department_Master_ListCreate.as_view(), name='Department_Maste_list-create'),
    path('Department_Maste/<int:pk>/', Department_Master_RetrieveUpdateDestroy.as_view(), name='Department_Maste_retrieve-update-destroy'),
    path('Department_Category_Master/', Department_Category_Master_ListCreate.as_view(), name='Department_Maste_list-create'),
    path('Department_Category_Master/<int:pk>/', Department_Category_Master_RetrieveUpdateDestroy.as_view(), name='Department_Maste_retrieve-update-destroy'),
    path('Designation_Api/', Designation_Api_ListCreate.as_view(), name='Designation_Api_list-create'),
    path('Designation_Api/<int:pk>/', Designation_Api_RetrieveUpdateDestroy.as_view(), name='Designation_Api_retrieve-update-destroy'),
    path('Contractor_Api/', Contractor_Api_ListCreate.as_view(), name='Contractor_Api_list-create'),
    path('Contractor_Api/<int:pk>/', Contractor_Api_RetrieveUpdateDestroy.as_view(), name='Contractor_Api_retrieve-update-destroy'),
    path('Unit_Conversion/', Unit_Conversion_ListCreate.as_view(), name='Unit_Conversion_list-create'),
    path('Unit_Conversion/<int:pk>/', Unit_Conversion_RetrieveUpdateDestroy.as_view(), name='Unit_Conversion_retrieve-update-destroy'),
    path('Contractor_Master/', Contractor_Master_ListCreate.as_view(), name='Contractor_Master_list-create'),
    path('Contractor_Master/<int:pk>/', Contractor_Master_RetrieveUpdateDestroy.as_view(), name='Contractor_Master_retrieve-update-destroy'),
    path('Item_Master_Data2/', Item_Master_Data2_ListCreate.as_view(), name='Item_Master_Data2_list-create'),
    path('Item_Master_Data2/<int:pk>/', Item_Master_Data2_RetrieveUpdateDestroy.as_view(), name='Item_Master_Data2_retrieve-update-destroy'),
    path('Technical_Specification/', Technical_Specification_ListCreate.as_view(), name='Technical_Specification_list-create'),
    path('Technical_Specification/<int:pk>/', Technical_Specification_RetrieveUpdateDestroy.as_view(), name='Technical_Specification_retrieve-update-destroy'),
    path('NPD/', NPD_ListCreate.as_view(), name='NPD_list-create'),
    path('NPD/<int:pk>/', NPD_RetrieveUpdateDestroy.as_view(), name='NPD_retrieve-update-destroy'),
    path('MainGroup/',  MainGroup_ListCreate.as_view(), name='MainGroup_list-create'),
    path('MainGroup/<int:pk>/', MainGroup_RetrieveUpdateDestroy.as_view(), name='MainGroup_retrieve-update-destroy'),
    path('UnitCode/', UnitCode_ListCreate.as_view(), name='UnitCode_list-create'),
    path('UnitCode/<int:pk>/', UnitCode_RetrieveUpdateDestroy.as_view(), name='UnitCode_retrieve-update-destroy'),
    path('TDC/', TDC_ListCreate.as_view(), name='TDC_Master_list-create'),
    path('TDC/<int:pk>/', TDC_RetrieveUpdateDestroy.as_view(), name='TDC_retrieve-update-destroy'),
    path('MetalType/', MetalType_ListCreate.as_view(), name='MetalType_list-create'),
    path('MetalType/<int:pk>/', MetalType_RetrieveUpdateDestroy.as_view(), name='MetalType_retrieve-update-destroy'),
    path('Item_Group/', Item_Group_ListCreate.as_view(), name='Contractor_Master_list-create'),
    path('Item_Group/<int:pk>/', Item_Group_RetrieveUpdateDestroy.as_view(), name='Contractor_Master_retrieve-update-destroy'),
    path('Store_Location/', Store_Location_ListCreate.as_view(), name='Store_Location_list-create'),
    path('Store_Location/<int:pk>/', Store_Location_RetrieveUpdateDestroy.as_view(), name='Store_Location_retrieve-update-destroy'),
    path('Route/', Route_ListCreate.as_view(), name='Route_list-create'),
    path('Route/<int:pk>/', Route_RetrieveUpdateDestroy.as_view(), name='Route_retrieve-update-destroy'),
    path('Parent_FG_Code/', Parent_FG_Code_ListCreate.as_view(), name='Parent_FG_Code_list-create'),
    path('Parent_FG_Code/<int:pk>/', Parent_FG_Code_RetrieveUpdateDestroy.as_view(), name='Parent_FG_Code_retrieve-update-destroy'),
    path('Sector_Item/', Sector_Item_master_ListCreate.as_view(), name='Sector_Item_list-create'),
    path('Sector_Item/<int:pk>/', Sector_Item_master_RetrieveUpdateDestroy.as_view(), name='Contractor_Master_retrieve-update-destroy'),
    path('Item_Section/', Item_Section_ListCreate.as_view(), name='Item_Section_list-create'),
    path('Item_Section/<int:pk>/', Item_Section_RetrieveUpdateDestroy.as_view(), name='Item_Section_retrieve-update-destroy'),
    path('Cost_Center/', Cost_Center_Master_ListCreate.as_view(), name='Cost_Center_list-create'),
    path('Cost_Center/<int:pk>/', Cost_Center_Master_RetrieveUpdateDestroy.as_view(), name='Cost_Center_retrieve-update-destroy'),
    path('Cost_Center_Master_Add_New/', Cost_Center_Master_Add_New_ListCreate.as_view(), name='Cost_Center_Master_Add_New_list-create'),
    path('Cost_Center_Master_Add_New/<int:pk>/', Cost_Center_Master_Add_New_RetrieveUpdateDestroy.as_view(), name='Cost_Center_Master_Add_New_retrieve-update-destroy'),
    path('Add_Price_List/', Add_Price_List_ListCreate.as_view(), name='Add_Price_List_list-create'),
    path('Add_Price_List/<int:pk>/', Add_Price_List_RetrieveUpdateDestroy.as_view(), name='Add_Price_List_retrieve-update-destroy'),
    path('Price_List_Entry/', Price_List_Entry_ListCreate.as_view(), name='Price_List_Entry_list-create'),
    path('Price_List_Entry/<int:pk>/', Price_List_Entry_RetrieveUpdateDestroy.as_view(), name='Price_List_Entry_retrieve-update-destroy'),
    path('Type_Grade_New/', Type_Grade_New_ListCreate.as_view(), name='Type_Grade_New_list-create'),
    path('Type_Grade_New/<int:pk>/', Type_Grade_New_RetrieveUpdateDestroy.as_view(), name='Type_Grade_New_retrieve-update-destroy'),
    path('Sub_Group/', Sub_Group_ListCreate.as_view(), name='Sub_Group_list-create'),
    path('Sub_Group/<int:pk>/', Sub_Group_RetrieveUpdateDestroy.as_view(), name='Sub_Group_retrieve-update-destroy'),
    path('Qty_Packing/', Qty_Packing_ListCreate.as_view(), name='Qty_Packing_list-create'),
    path('Qty_Packing/<int:pk>/', Qty_Packing_RetrieveUpdateDestroy.as_view(), name='Qty_Packing_retrieve-update-destroy'),
    path('Production_Department/', Production_Department_ListCreate.as_view(), name='Production_Department_list-create'),
    path('Production_Department/<int:pk>/', Production_Department_RetrieveUpdateDestroy.as_view(), name='Production_Department_retrieve-update-destroy'),
    path('Operation_Master/', Operation_Master_ListCreate.as_view(), name='Operation_Master_list-create'),
    path('Operation_Master/<int:pk>/', Operation_Master_RetrieveUpdateDestroy.as_view(), name='Operation_Master_retrieve-update-destroy'),
    path('Std_Routing/', Std_Routing_ListCreate.as_view(), name='Std_Routing_list-create'),
    path('Std_Routing/<int:pk>/', Std_Routing_RetrieveUpdateDestroy.as_view(), name='Std_Routing_retrieve-update-destroy'),
    path('Bom_Item_Group/', Bom_Item_Group_ListCreate.as_view(), name='Bom_Item_Group_list-create'),
    path('Bom_Item_Group/<int:pk>/', Bom_Item_Group_RetrieveUpdateDestroy.as_view(), name='Bom_Item_Group_retrieve-update-destroy'),
    path('Fetch_Region/', Fetch_Region_ListCreate.as_view(), name='Fetch_Region_list-create'),
    path('Cross_Ref_Supplier/', Cross_Ref_Supplier_ListCreate.as_view(), name='Cross_Ref_Supplier_list-create'), 
    path('get-state-data/', get_state_data, name='get_state_data'),
    path('api/tax/<str:state_code>/', TaxTypeView.as_view(), name='tax_type'),
    path('SupplierType/entity/<str:entity_type>/', EntityView.as_view(), name='entity-view'),
    path('gst-info/', GSTNumberInfoView.as_view(), name='gst-info'),
    path('UnitCodeHardCoded/', UnitCodeHardCodeListView.as_view(), name='UnitCodeHardCoded/-list'),
    # path('next-part-no/<int:main_group_id>/<int:item_group_id>/', NextPartNoAPIView.as_view(), name='next-part-no'),
    path('api/items/', ItemViewSet.as_view({'get': 'list', 'post': 'create'}), name='item-list'),
    path('api/items/<int:pk>/', ItemViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name='item-detail'),
    path('get-next-item-number/', GetNextItemNumber.as_view(), name='get-next-item-number'),
    path('api/item/<int:pk>/pdf-data/', ItemPDFDataAPIView.as_view(), name='item-pdf-data'),
    path('api/item/pdf/<int:pk>/', generate_item_pdf, name='supplier-pdf'),
    path('SupplierCustomerVendorList/', ItemSummaryAPIView.as_view(), name='item-summary'),
    path('api/export-items/', export_items_to_excel, name='export_items_excel'),
    # path('api/item-table/pdf/<int:pk>/', generate_itemtable_pdf, name='itemtable_pdf'),
    # path('ItemMasterList/', ItemMasterAPIView.as_view(), name='item-summary'),
    path('ItemMaster/pdf/<int:pk>/', generate_ItemMaster_pdf, name='item_pdf'),
    path('api/item/summary/', ItemMasterAPIView.as_view(), name='item_summary'),
    path('api/item/detail/<int:pk>/', ItemDetailAPIView.as_view(), name='item_detail'),
    path('generate-code/', generate_code),
    path('api/operations/', OperationDropdownView.as_view(), name='operation-dropdown'),
    path('api/items/<int:item_id>/boms/', BOMListCreateAPIView.as_view(), name='bom-list-create'),
    path('api/items/<int:item_id>/boms/<int:bom_id>/', UpdateBOMAPIView.as_view(), name='update-bom'),
    path('api/items/<int:item_id>/boms/<int:bom_id>/delete/', DeleteBOMAPIView.as_view(), name='delete-bom'),
    path('api/items/search/', ItemSearchWithBOMAPIView.as_view(), name='item-search-with-bom'),
    path('api/item-search/', ItemSearchView2.as_view(), name='item-search'),
    path('FetchScrap/', ItemTableScrapListView.as_view(), name='item-table-scrap'),
    path('api/item/create/', CreateItemAPIView.as_view(), name='create-item'),
    path('api/item/<str:part_no>/', GetItemDetailsAPIView.as_view(), name='get-item-details'),
    path('api/transaction/create/', ItemTransactionCreateAPIView.as_view(), name='create-item-txn'),
    path('api/transaction/<int:pk>/', ItemTransactionDetailAPIView.as_view(), name='get-item-txn'),
    path('Fetch_Item_fields/', ItemSearchView5.as_view(), name='item-search'),
    path('api/transaction/create2/', ItemTransactionCreateAPIView2.as_view(), name='create-item-txn'),
    path('api/transaction2/<int:pk>/', ItemTransactionDetailAPIView2.as_view(), name='get-item-txn'),
    path('api/combine-partno/', CombinedPartNoAPIView.as_view()),
    path('api/rm-items/', RMItemSearchView.as_view(), name='rm-item-search'),
    path('BOM_ItemPartMaster/item/<int:item_id>/bom/', BOM_ItemPartMaster_ListCreate.as_view(), name='bom-list-create'),
    path('api/item/<int:item_id>/bom/<int:pk>/', BOM_ItemPartMaster_RetrieveUpdateDestroy.as_view(), name='bom-detail'),
    path('api/item/<int:item_id>/bom/dropdown/', BOMDropdownAPIView.as_view(), name='bom-dropdown'),
    path('bom/simple-search/<int:item_id>/', BOMItemSimpleSearch.as_view(), name='simple-search'),
    path("api/bom_pdf/<int:item_id>/",views.generate_bom_pdf,name='generate_bom_pdf'),
    path('api/bom-items/', BOMItemByPartCodeView.as_view(), name='bom-items-by-part-code'),

    path('supplier/delete/<int:item_id>', ItemDeleteAPI.as_view() , name='supplier-item-delete' ),
    path('item/delete/<int:item_id>' , ItemtableDeleteAPI.as_view() , name='Item-table-delete'),
    path('bom/delete/<int:bom_id>', BOMItemDeleteAPI.as_view(), name='bomitem-delete'),    
    
    path('cycle/time/list' , Cycletimemasterlist.as_view(),name='life-cycle-time-list'),
    path("cycle/master/item/", Cyclemasterlistitem.as_view(), name='cycle-item-dropdown-list'),

    path('tools/', ToolManagementAPIView.as_view(), name='tools-add-operation-wise'),
    path('item-master-filtered/', ItemMasterFilteredAPIView.as_view(), name='item-master-filtered' ),
    path(
        "operation-master/",
        OperationMasterAPIView.as_view(),
        name="operation-master",
    ),

    path(
    "FG-items/",
    FGItemRMSearchView.as_view(),
    name="fg-items-rm"
    ),
    path('item-report/',ItemReportAPIView.as_view(),name='item-report'),
    path('item-duplicate-search/',ItemDuplicateSearchAPIView.as_view(),name='item-duplicate-search'),
    path('customer-supplier-duplicate-search/',CustomerSupplierDuplicateSearchAPIView.as_view(),name='customer-supplier-duplicate-search'),
]
