# Generated by Django 5.2.8 on 2026-05-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=3000, null=True)),
                ('so_no_date', models.DateField(blank=True, null=True)),
                ('po_no_date', models.DateField(blank=True, null=True)),
                ('schedule_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('item_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('item_code', models.CharField(blank=True, max_length=3000, null=True)),
                ('item_description', models.CharField(blank=True, max_length=3000, null=True)),
                ('sch_rec_on', models.DateField(blank=True, null=True)),
                ('sch_qty', models.CharField(blank=True, max_length=3000, null=True)),
                ('buffer_qty', models.CharField(blank=True, max_length=3000, null=True)),
                ('next_month_sc', models.CharField(blank=True, max_length=3000, null=True)),
                ('due_dispatch_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
