# Generated by Django 5.2.8 on 2026-05-05 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planning', '0001_initial'),
        ('Settings', '0004_alter_schedulemonthmaster_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionschedule',
            name='schedule_month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_schedules', to='Settings.schedulemonthmaster'),
        ),
    ]
