# Generated by Django 5.2.8 on 2026-05-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planning', '0002_productionschedule_schedule_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateItemWiseMinMax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(blank=True, max_length=500, null=True)),
                ('item_code', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('item_groups', models.CharField(blank=True, max_length=500, null=True)),
                ('main_groups', models.CharField(blank=True, max_length=500, null=True)),
                ('unit', models.CharField(blank=True, max_length=500, null=True)),
                ('tariff_no', models.CharField(blank=True, max_length=500, null=True)),
                ('min_level', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('re_order_level', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('max_level', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('min_order', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('max_order', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('grn_tol_sub', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('grn_tol_add', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('user', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
