# Generated by Django 5.2.8 on 2026-05-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planning', '0003_updateitemwiseminmax'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date', models.DateField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=500, null=True)),
                ('item', models.CharField(blank=True, max_length=500, null=True)),
                ('stock', models.CharField(blank=True, max_length=500, null=True)),
                ('plan_quantity', models.CharField(blank=True, max_length=500, null=True)),
                ('heat_code', models.CharField(blank=True, max_length=500, null=True)),
                ('heat_no', models.CharField(blank=True, max_length=500, null=True)),
                ('cust_ref_challan_no', models.CharField(blank=True, max_length=500, null=True)),
                ('po_no', models.CharField(blank=True, max_length=500, null=True)),
                ('select_material', models.CharField(blank=True, max_length=500, null=True)),
                ('machine', models.CharField(blank=True, max_length=500, null=True)),
                ('die_no', models.CharField(blank=True, max_length=500, null=True)),
                ('material', models.TextField(blank=True, null=True)),
                ('weigth', models.CharField(blank=True, max_length=500, null=True)),
                ('tray_weigth', models.CharField(blank=True, max_length=500, null=True)),
                ('dept_ppc', models.CharField(blank=True, max_length=500, null=True)),
                ('dept_cc', models.CharField(blank=True, max_length=500, null=True)),
                ('optional_fields', models.BooleanField(blank=True, default=False)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
