# Generated by Django 5.0.6 on 2025-05-08 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialyear',
            name='user',
        ),
    ]
