# Generated by Django 5.2.8 on 2026-05-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0003_schedulemonthmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulemonthmaster',
            name='user',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
