# Generated by Django 5.2.8 on 2026-02-23 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InwardtestQCinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qc_no', models.CharField(blank=True, max_length=300, null=True)),
                ('sample_qty', models.CharField(blank=True, max_length=300, null=True)),
                ('prod_qty', models.CharField(blank=True, max_length=300, null=True)),
                ('qc_qty', models.CharField(blank=True, max_length=300, null=True)),
                ('ok_qty', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('qc_time', models.TimeField(blank=True, null=True)),
                ('a_u_d_qty', models.CharField(blank=True, max_length=300, null=True)),
                ('drawing_rev_no', models.CharField(blank=True, max_length=300, null=True)),
                ('format_no', models.CharField(blank=True, max_length=300, null=True)),
                ('rev_no', models.CharField(blank=True, max_length=300, null=True)),
                ('rev_date', models.DateField(blank=True, null=True)),
                ('accepted_or_rejected', models.TextField(blank=True, max_length=3000, null=True)),
                ('accepted_under_deviation', models.TextField(blank=True, max_length=3000, null=True)),
                ('suggestion', models.TextField(blank=True, max_length=3000, null=True)),
                ('inspected_by', models.CharField(blank=True, max_length=300, null=True)),
                ('remark', models.TextField(blank=True, max_length=3000, null=True)),
                ('non_conformece', models.TextField(blank=True, max_length=3000, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=3000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InwardtestDimensional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('test_description', models.CharField(blank=True, max_length=3000, null=True)),
                ('specification', models.CharField(blank=True, max_length=3000, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=3000, null=True)),
                ('tol_sub', models.CharField(blank=True, max_length=3000, null=True)),
                ('tol_add', models.CharField(blank=True, max_length=3000, null=True)),
                ('methods_of_check', models.CharField(blank=True, max_length=3000, null=True)),
                ('one', models.CharField(blank=True, max_length=3000, null=True)),
                ('two', models.CharField(blank=True, max_length=3000, null=True)),
                ('three', models.CharField(blank=True, max_length=3000, null=True)),
                ('four', models.CharField(blank=True, max_length=3000, null=True)),
                ('five', models.CharField(blank=True, max_length=3000, null=True)),
                ('remark', models.TextField(blank=True, max_length=250, null=True)),
                ('actual_observation', models.CharField(blank=True, max_length=250, null=True)),
                ('qc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_tests', to='Quality.inwardtestqcinfo')),
            ],
        ),
        migrations.CreateModel(
            name='InwardtestrejectQty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=3000, null=True)),
                ('qty', models.CharField(blank=True, max_length=3000, null=True)),
                ('qc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reject_qty', to='Quality.inwardtestqcinfo')),
            ],
        ),
        migrations.CreateModel(
            name='InwardtestreworkQty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=3000, null=True)),
                ('qty', models.CharField(blank=True, max_length=3000, null=True)),
                ('qc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rework_qty', to='Quality.inwardtestqcinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Inwardtestvisulainspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('test_description', models.CharField(blank=True, max_length=3000, null=True)),
                ('specification', models.CharField(blank=True, max_length=3000, null=True)),
                ('methods_of_check', models.CharField(blank=True, max_length=3000, null=True)),
                ('one', models.CharField(blank=True, max_length=3000, null=True)),
                ('two', models.CharField(blank=True, max_length=3000, null=True)),
                ('three', models.CharField(blank=True, max_length=3000, null=True)),
                ('four', models.CharField(blank=True, max_length=3000, null=True)),
                ('five', models.CharField(blank=True, max_length=3000, null=True)),
                ('merge', models.BooleanField(default=True)),
                ('remark', models.TextField(blank=True, max_length=250, null=True)),
                ('qc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visual_tests', to='Quality.inwardtestqcinfo')),
            ],
        ),
    ]
