# Generated by Django 5.2.8 on 2026-02-24 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubconJobworkQCInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qc', models.CharField(blank=True, max_length=300, null=True)),
                ('qc_date', models.DateTimeField(blank=True, null=True)),
                ('format_no', models.CharField(blank=True, null=True)),
                ('vendor_heat_code', models.CharField(blank=True, max_length=300, null=True)),
                ('vendor_tc_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('rev_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('lot_accepted_rejected', models.CharField(blank=True, max_length=3000, null=True)),
                ('sample_qty', models.CharField(blank=True, max_length=300, null=True)),
                ('rev_date', models.DateField(blank=True, null=True)),
                ('control_plan_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('wire_size', models.CharField(blank=True, max_length=3000, null=True)),
                ('total_coil', models.CharField(blank=True, max_length=3000, null=True)),
                ('coil_from_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('coil_to_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('heat_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('grn_qty', models.CharField(blank=True, max_length=3000, null=True)),
                ('qc_pending_qty', models.CharField(blank=True, max_length=3000, null=True)),
                ('qc_qty', models.CharField(blank=True, max_length=3000, null=True)),
                ('ok_qty', models.CharField(blank=True, max_length=3000, null=True)),
                ('rework_qty', models.CharField(blank=True, max_length=3000, null=True)),
                ('reject_qty', models.CharField(blank=True, max_length=3000, null=True)),
                ('store_qty', models.CharField(blank=True, max_length=3000, null=True)),
                ('a_u_d_qty', models.CharField(blank=True, max_length=3000, null=True)),
                ('raw_material', models.CharField(blank=True, max_length=3000, null=True)),
                ('drawing_rev_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('lab_mill_tc_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('lab_mill_tc_name', models.CharField(blank=True, max_length=3000, null=True)),
                ('lab_mill_tc_date', models.DateField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubconJobworkDimensional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('test_description', models.CharField(blank=True, max_length=3000, null=True)),
                ('specification', models.CharField(blank=True, max_length=3000, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=3000, null=True)),
                ('tol_sub', models.CharField(blank=True, max_length=3000, null=True)),
                ('tol_add', models.CharField(blank=True, max_length=3000, null=True)),
                ('methods_of_check', models.CharField(blank=True, max_length=3000, null=True)),
                ('one', models.CharField(blank=True, max_length=3000, null=True)),
                ('two', models.CharField(blank=True, max_length=3000, null=True)),
                ('three', models.CharField(blank=True, max_length=3000, null=True)),
                ('four', models.CharField(blank=True, max_length=3000, null=True)),
                ('five', models.CharField(blank=True, max_length=3000, null=True)),
                ('remark', models.TextField(blank=True, max_length=250, null=True)),
                ('qc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_tests', to='Quality.subconjobworkqcinfo')),
            ],
        ),
        migrations.CreateModel(
            name='SubconJobworkrejectQty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=3000, null=True)),
                ('qty', models.CharField(blank=True, max_length=3000, null=True)),
                ('supplier', models.CharField(blank=True, max_length=3000, null=True)),
                ('qc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reject_items', to='Quality.subconjobworkqcinfo')),
            ],
        ),
        migrations.CreateModel(
            name='SubconJobworkreworkQty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=3000, null=True)),
                ('qty', models.CharField(blank=True, max_length=3000, null=True)),
                ('supplier', models.CharField(blank=True, max_length=3000, null=True)),
                ('qc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rework_items', to='Quality.subconjobworkqcinfo')),
            ],
        ),
        migrations.CreateModel(
            name='SubconJobworkvisulainspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('test_description', models.CharField(blank=True, max_length=3000, null=True)),
                ('specification', models.CharField(blank=True, max_length=3000, null=True)),
                ('methods_of_check', models.CharField(blank=True, max_length=3000, null=True)),
                ('one', models.CharField(blank=True, max_length=3000, null=True)),
                ('two', models.CharField(blank=True, max_length=3000, null=True)),
                ('three', models.CharField(blank=True, max_length=3000, null=True)),
                ('four', models.CharField(blank=True, max_length=3000, null=True)),
                ('five', models.CharField(blank=True, max_length=3000, null=True)),
                ('merge', models.BooleanField(default=True)),
                ('remark', models.TextField(blank=True, max_length=250, null=True)),
                ('qc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visual_tests', to='Quality.subconjobworkqcinfo')),
            ],
        ),
    ]
