# Generated by Django 5.2.8 on 2026-02-25 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quality', '0002_subconjobworkqcinfo_subconjobworkdimensional_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReturnQcInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejection_series', models.CharField(blank=True, max_length=3000, null=True)),
                ('qc_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('qc_date', models.DateField(blank=True, null=True)),
                ('cust_vender_name', models.CharField(blank=True, max_length=3000, null=True)),
                ('select_item', models.CharField(blank=True, max_length=3000, null=True)),
                ('part_code', models.CharField(blank=True, max_length=3000, null=True)),
                ('heat_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('New_heat_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('return_qty', models.CharField(blank=True, max_length=3000, null=True)),
                ('ok_qty', models.CharField(blank=True, max_length=3000, null=True)),
                ('rework_qty', models.CharField(blank=True, max_length=3000, null=True)),
                ('reject_qty', models.CharField(blank=True, max_length=3000, null=True)),
                ('rework_reason', models.CharField(blank=True, max_length=3000, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=3000, null=True)),
                ('action_plan', models.CharField(blank=True, max_length=3000, null=True)),
                ('action', models.CharField(blank=True, max_length=3000, null=True)),
                ('action_date', models.DateField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, max_length=250, null=True)),
                ('inspected_by', models.CharField(blank=True, max_length=3000, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=3000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturnDimensional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('test_description', models.CharField(blank=True, max_length=3000, null=True)),
                ('specification', models.CharField(blank=True, max_length=3000, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=3000, null=True)),
                ('tol_sub', models.CharField(blank=True, max_length=3000, null=True)),
                ('tol_add', models.CharField(blank=True, max_length=3000, null=True)),
                ('methods_of_check', models.CharField(blank=True, max_length=3000, null=True)),
                ('one', models.CharField(blank=True, max_length=3000, null=True)),
                ('two', models.CharField(blank=True, max_length=3000, null=True)),
                ('three', models.CharField(blank=True, max_length=3000, null=True)),
                ('four', models.CharField(blank=True, max_length=3000, null=True)),
                ('five', models.CharField(blank=True, max_length=3000, null=True)),
                ('remark', models.TextField(blank=True, max_length=250, null=True)),
                ('qc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_tests', to='Quality.salesreturnqcinfo')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturnvisulainspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('test_description', models.CharField(blank=True, max_length=3000, null=True)),
                ('check_points', models.CharField(blank=True, max_length=3000, null=True)),
                ('actual_observation', models.CharField(blank=True, max_length=3000, null=True)),
                ('one', models.CharField(blank=True, max_length=3000, null=True)),
                ('two', models.CharField(blank=True, max_length=3000, null=True)),
                ('three', models.CharField(blank=True, max_length=3000, null=True)),
                ('four', models.CharField(blank=True, max_length=3000, null=True)),
                ('five', models.CharField(blank=True, max_length=3000, null=True)),
                ('merge', models.BooleanField(default=True)),
                ('remark', models.TextField(blank=True, max_length=250, null=True)),
                ('qc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visual_tests', to='Quality.salesreturnqcinfo')),
            ],
        ),
    ]
