# Generated by Django 5.2.8 on 2026-03-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quality', '0003_salesreturnqcinfo_salesreturndimensional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subconjobworkqcinfo',
            name='grn_57F4_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subconjobworkqcinfo',
            name='grn_57F4_no',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='subconjobworkqcinfo',
            name='vendor',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
