# Generated by Django 5.2.8 on 2026-03-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quality', '0004_subconjobworkqcinfo_grn_57f4_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subconjobworkqcinfo',
            name='item',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
