# Generated by Django 5.2.8 on 2026-04-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quality', '0005_subconjobworkqcinfo_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subconjobworkqcinfo',
            name='format_no',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
