# Generated by Django 6.0.5 on 2026-08-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quality', '0006_alter_subconjobworkqcinfo_format_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwardtestqcinfo',
            name='heat_no',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='inwardtestqcinfo',
            name='item',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='inwardtestqcinfo',
            name='item_des',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='inwardtestqcinfo',
            name='opno',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='inwardtestqcinfo',
            name='prod_no',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
