# Generated by Django 6.0.5 on 2026-05-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToolManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(blank=True, max_length=500, null=True)),
                ('item_description', models.CharField(blank=True, max_length=500, null=True)),
                ('part_code', models.CharField(blank=True, max_length=200, null=True)),
                ('tool_code', models.CharField(blank=True, max_length=500, null=True)),
                ('tool_description', models.CharField(blank=True, max_length=500, null=True)),
                ('make', models.CharField(blank=True, max_length=200, null=True)),
                ('tool_life', models.CharField(blank=True, max_length=200, null=True)),
                ('no_of_reshaping_tool', models.CharField(blank=True, max_length=500, null=True)),
                ('total_life', models.CharField(blank=True, max_length=200, null=True)),
                ('total_required', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
