# Generated by Django 6.0.5 on 2026-05-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolmanagement',
            name='total_required',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=50, null=True),
        ),
    ]
