# Generated by Django 5.2.3 on 2025-07-03 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallanCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='onwardchallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_no', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('item_code', models.CharField(default='DEFAULT_ITEM', max_length=100)),
                ('challan_date', models.DateField()),
                ('challan_time', models.TimeField()),
                ('DC_no', models.CharField(blank=True, max_length=300)),
                ('Transport_name', models.CharField(blank=True, max_length=100)),
                ('vehical_no', models.CharField(blank=True, max_length=300)),
                ('Estimated_value', models.CharField(blank=True, max_length=300)),
                ('DC_date', models.DateField()),
                ('EWay_bill_no', models.CharField(blank=True, max_length=300)),
                ('eway_bill_date', models.DateField(blank=True, null=True)),
                ('rev_charges', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('rec_ch_amt', models.CharField(blank=True, max_length=300)),
                ('Eway_bill_Qty', models.CharField(blank=True, max_length=300, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('plant', models.CharField(blank=True, default='', max_length=300)),
                ('series', models.CharField(blank=True, max_length=300)),
                ('vender', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='transportdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.IntegerField(unique=True)),
                ('transport_name', models.CharField(max_length=300)),
                ('EWAY_bill_no', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='vehicaldetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.IntegerField(unique=True)),
                ('customer', models.CharField(blank=True, max_length=300)),
                ('vehical_no', models.CharField(max_length=300, validators=[django.core.validators.RegexValidator(message='Enter a valid Indian vehicle number (e.g., MH12AB1234)', regex='^[A-Z]{2}\\s?[0-9]{1,2}\\s?[A-Z]{1,3}\\s?[0-9]{1,4}$')])),
            ],
        ),
    ]
