# Generated by Django 5.2.3 on 2025-07-04 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0002_challancounter_onwardchallan_transportdetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onwardchallan',
            name='item_code',
        ),
        migrations.CreateModel(
            name='OnwardChallanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(default='DEFAULT_ITEM', max_length=100)),
                ('type', models.CharField(max_length=3000)),
                ('description', models.CharField(blank=True, max_length=3000)),
                ('store', models.CharField(max_length=100)),
                ('suppRefNo', models.CharField(max_length=300)),
                ('qtyNo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qtyKg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('process', models.CharField(blank=True, max_length=100)),
                ('pkg', models.CharField(blank=True, max_length=300)),
                ('wRate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('wValue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Sales.onwardchallan')),
            ],
        ),
    ]
