# Generated by Django 5.2.3 on 2025-07-16 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_remove_onwardchallan_item_code_onwardchallanitem'),
        ('Store', '0016_alter_newmrn_approve_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='onwardchallanitem',
            name='grn_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.grngenraldetail'),
        ),
    ]
