# Generated by Django 5.2.3 on 2025-07-16 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0004_onwardchallanitem_grn_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onwardchallanitem',
            name='grn_detail',
        ),
    ]
