# Generated by Django 5.2.5 on 2025-10-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0005_remove_onwardchallanitem_grn_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('available_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
    ]
