# Generated by Django 5.2.5 on 2025-10-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0006_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='onwardchallanitem',
            name='stock',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
