# Generated by Django 5.2.8 on 2025-12-25 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0008_invoice_newsalesorder_invoiceitemdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsalesorder',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='newsales/'),
        ),
        migrations.CreateModel(
            name='GstdetailsInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_value', models.IntegerField(blank=True, max_length=10, null=True)),
                ('disc_amt', models.IntegerField(blank=True, max_length=10, null=True)),
                ('rev_base_crg', models.IntegerField(blank=True, max_length=10, null=True)),
                ('rev_charg_amt', models.IntegerField(blank=True, max_length=10, null=True)),
                ('tcs', models.IntegerField(blank=True, max_length=10, null=True)),
                ('assessble_value', models.IntegerField(blank=True, max_length=10, null=True)),
                ('cgst', models.IntegerField(blank=True, max_length=10, null=True)),
                ('sgst', models.IntegerField(blank=True, max_length=10, null=True)),
                ('igst', models.IntegerField(blank=True, max_length=10, null=True)),
                ('utgst', models.IntegerField(blank=True, max_length=10, null=True)),
                ('pack_fwrd', models.IntegerField(blank=True, max_length=10, null=True)),
                ('transport_crg', models.IntegerField(blank=True, max_length=10, null=True)),
                ('freight_crg', models.IntegerField(blank=True, max_length=10, null=True)),
                ('other_crg', models.IntegerField(blank=True, max_length=10, null=True)),
                ('grand_total', models.IntegerField(blank=True, max_length=300, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GSTdetails', to='Sales.invoice')),
            ],
        ),
    ]
