# Generated by Django 5.2.8 on 2025-12-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0009_alter_newsalesorder_file_gstdetailsinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsalesitemdetails',
            name='plan_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newsalesorder',
            name='plan_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newsalesorder',
            name='po_rec_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newsalesorder',
            name='shift',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsalesorder',
            name='so_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
