# Generated by Django 5.2.8 on 2025-12-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0010_alter_newsalesitemdetails_plan_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='pdi_no',
        ),
    ]
