# Generated by Django 5.2.8 on 2025-12-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0011_remove_invoice_bank_remove_invoice_pdi_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsalesorder',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='newsales/'),
        ),
    ]
