# Generated by Django 5.2.8 on 2026-01-30 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0012_alter_newsalesorder_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=300, null=True)),
                ('notetype', models.CharField(blank=True, max_length=100, null=True)),
                ('debit_note_no', models.CharField(blank=True, max_length=100, null=True)),
                ('debit_note_date', models.DateField()),
                ('party_name', models.CharField(blank=True, max_length=250, null=True)),
                ('mode_of_transport', models.CharField(blank=True, max_length=100, null=True)),
                ('lr_gc_note_no', models.CharField(blank=True, max_length=100, null=True)),
                ('eway_bill_no', models.CharField(blank=True, max_length=100, null=True)),
                ('eway_bill_date', models.DateField()),
                ('vehical_no', models.CharField(blank=True, max_length=100, null=True)),
                ('traspoter', models.CharField(blank=True, max_length=100, null=True)),
                ('po_no', models.CharField(blank=True, max_length=100, null=True)),
                ('po_date', models.DateField()),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_date', models.DateField()),
                ('remark', models.CharField(blank=True, max_length=250, null=True)),
                ('is_service_dn', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DebitNoteIteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_no', models.CharField(blank=True, max_length=100, null=True)),
                ('grn_date', models.DateField()),
                ('item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('item_description', models.CharField(blank=True, max_length=100, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=100, null=True)),
                ('grn_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('stock', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('remark', models.CharField(blank=True, max_length=250, null=True)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('Rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('transport_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('utgst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tcs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tds_on_basic', models.BooleanField(default=True)),
                ('tds_on_grand_total', models.BooleanField(default=False)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('debit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Sales.debitnote')),
            ],
        ),
    ]
