# Generated by Django 5.2.8 on 2026-02-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0013_debitnote_debitnoteiteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitnote',
            name='debit_note_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='eway_bill_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='po_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debitnoteiteam',
            name='grn_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
