# Generated by Django 5.2.8 on 2026-02-03 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0014_alter_debitnote_debit_note_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newgstsalesreturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(blank=True, max_length=100, null=True)),
                ('gate_entry_no', models.CharField(blank=True, max_length=300, null=True)),
                ('series', models.CharField(blank=True, max_length=300, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_return_no', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_return_date', models.DateField(blank=True, null=True)),
                ('cust_name', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_challan_no', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_challan_date', models.DateField(blank=True, null=True)),
                ('transport_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Lr_no', models.CharField(blank=True, max_length=100, null=True)),
                ('vehical_no', models.CharField(blank=True, max_length=300, null=True)),
                ('remark', models.CharField(blank=True, max_length=250, null=True)),
                ('for_e_invoice', models.CharField(blank=True, max_length=250, null=True)),
                ('is_service', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewgstsalesItemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_no', models.CharField(blank=True, max_length=100, null=True)),
                ('inv_date', models.DateField(blank=True, null=True)),
                ('item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=100, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('inv_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('return_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('lot', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('grir_no', models.CharField(blank=True, max_length=100, null=True)),
                ('grir_date', models.DateField(blank=True, null=True)),
                ('basic', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('disc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('utgst', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('toc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tsc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('new_gst_sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Sales.newgstsalesreturn')),
            ],
        ),
    ]
