# Generated by Django 5.2.8 on 2026-02-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0015_newgstsalesreturn_newgstsalesitemdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsalesitemdetails',
            name='assessable_value',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='newsalesitemdetails',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='newsalesitemdetails',
            name='gr_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='newsalesitemdetails',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='newsalesitemdetails',
            name='igst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='newsalesitemdetails',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='newsalesitemdetails',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='newsalesitemdetails',
            name='utgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
