# Generated by Django 5.2.8 on 2026-02-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0016_newsalesitemdetails_assessable_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitemdetails',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
