# Generated by Django 5.2.8 on 2026-02-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0017_invoiceitemdetails_hsn_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsalesorder',
            name='so_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
