# Generated by Django 5.2.8 on 2026-02-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0019_alter_newsalesorder_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitemdetails',
            name='dis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
