# Generated by Django 5.2.8 on 2026-02-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0020_invoiceitemdetails_dis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstdetailsinvoice',
            name='assessble_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gstdetailsinvoice',
            name='base_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gstdetailsinvoice',
            name='cgst',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gstdetailsinvoice',
            name='disc_amt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gstdetailsinvoice',
            name='igst',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gstdetailsinvoice',
            name='pack_fwrd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gstdetailsinvoice',
            name='rev_base_crg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gstdetailsinvoice',
            name='rev_charg_amt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gstdetailsinvoice',
            name='sgst',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gstdetailsinvoice',
            name='tcs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gstdetailsinvoice',
            name='transport_crg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gstdetailsinvoice',
            name='utgst',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
