# Generated by Django 5.2.8 on 2026-02-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0021_alter_gstdetailsinvoice_assessble_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstdetailsinvoice',
            name='cgst_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='gstdetailsinvoice',
            name='igst_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='gstdetailsinvoice',
            name='sgst_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='gstdetailsinvoice',
            name='utgst_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='newgstsalesitemdetails',
            name='cgst_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='newgstsalesitemdetails',
            name='igst_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='newgstsalesitemdetails',
            name='sgst_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='newgstsalesitemdetails',
            name='utgst_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='newsalesitemdetails',
            name='cgst_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='newsalesitemdetails',
            name='igst_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='newsalesitemdetails',
            name='sgst_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='newsalesitemdetails',
            name='utgst_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='gstdetailsinvoice',
            name='freight_crg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gstdetailsinvoice',
            name='grand_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gstdetailsinvoice',
            name='other_crg',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
