# Generated by Django 5.2.8 on 2026-04-11 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0022_gstdetailsinvoice_cgst_amt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRateDiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_note_no', models.CharField(blank=True, max_length=300, null=True)),
                ('debit_note_date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=3000, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('dis_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ass_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('utgst', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tcs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cgst_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igst_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('utgst_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tcs_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('bill_to_add_code', models.CharField(blank=True, max_length=3000, null=True)),
                ('other_reference', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('for_e_invoice', models.CharField(blank=True, max_length=3000, null=True)),
                ('is_service_invoice', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SalesRateDiffItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=300, null=True)),
                ('item', models.CharField(blank=True, max_length=3000, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=3000, null=True)),
                ('qty', models.CharField(blank=True, max_length=3000, null=True)),
                ('old_rate', models.CharField(blank=True, max_length=3000, null=True)),
                ('new_rate', models.CharField(blank=True, max_length=3000, null=True)),
                ('dis', models.CharField(blank=True, max_length=3000, null=True)),
                ('diff', models.CharField(blank=True, max_length=3000, null=True)),
                ('diff_amt', models.CharField(blank=True, max_length=3000)),
                ('grir_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('grir_date', models.DateField(blank=True, null=True)),
                ('grir_qty', models.CharField(blank=True, max_length=3000, null=True)),
                ('line_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('po_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('amd_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('salesdiff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='Sales.salesratediff')),
            ],
        ),
    ]
