# Generated by Django 5.2.8 on 2026-04-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0023_salesratediff_salesratediffitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitemdetails',
            name='part_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitemdetails',
            name='part_no',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
