# Generated by Django 5.2.8 on 2026-04-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0024_invoiceitemdetails_part_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsalesitemdetails',
            name='item_no',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
