# Generated by Django 5.2.8 on 2026-04-24 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0025_newsalesitemdetails_item_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTJobworkInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(blank=True, max_length=3000, null=True)),
                ('series', models.CharField(blank=True, max_length=3000, null=True)),
                ('type', models.CharField(blank=True, max_length=3000, null=True)),
                ('gst_type', models.CharField(blank=True, max_length=3000, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('invoice_time', models.TimeField(blank=True, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('date_of_removal_of_goods', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('mode_of_transport', models.CharField(blank=True, max_length=3000, null=True)),
                ('vehical_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('transporter', models.CharField(blank=True, max_length=3000, null=True)),
                ('bill_to_cust', models.CharField(blank=True, max_length=3000, null=True)),
                ('addr_code', models.CharField(blank=True, max_length=3000, null=True)),
                ('place_of_supply', models.CharField(blank=True, max_length=3000, null=True)),
                ('ship_to_cust', models.CharField(blank=True, max_length=3000, null=True)),
                ('ship_to_addr_code', models.CharField(blank=True, max_length=3000, null=True)),
                ('lr_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('vehical_time', models.TimeField(blank=True, null=True)),
                ('vehical_out_time', models.TimeField(blank=True, null=True)),
                ('dc_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('bank', models.CharField(blank=True, max_length=3000, null=True)),
                ('dc_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GSTJobworkGSTDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_total', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('discount_per', models.CharField(blank=True, max_length=300, null=True)),
                ('discount_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('assessable_value', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=100, null=True)),
                ('cgst', models.CharField(blank=True, max_length=100, null=True)),
                ('sgst', models.CharField(blank=True, max_length=100, null=True)),
                ('igst', models.CharField(blank=True, max_length=100, null=True)),
                ('tcs', models.CharField(blank=True, max_length=100, null=True)),
                ('cgst_amt', models.DecimalField(blank=True, decimal_places=3, max_digits=50, null=True)),
                ('sgst_amt', models.DecimalField(blank=True, decimal_places=3, max_digits=50, null=True)),
                ('igst_amt', models.DecimalField(blank=True, decimal_places=3, max_digits=50, null=True)),
                ('tcs_amt', models.DecimalField(blank=True, decimal_places=3, max_digits=50, null=True)),
                ('e_invoice_type', models.CharField(blank=True, max_length=3000, null=True)),
                ('gr_total', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gst_details', to='Sales.gstjobworkinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='GSTJobworkItemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('line_pono', models.CharField(blank=True, max_length=3000, null=True)),
                ('line_podt', models.DateField(blank=True, null=True)),
                ('item_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('item_code', models.CharField(blank=True, max_length=3000, null=True)),
                ('description', models.CharField(blank=True, max_length=3000, null=True)),
                ('stock', models.CharField(blank=True, max_length=3000, null=True)),
                ('so_line_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('jobwork_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('rate_type', models.CharField(blank=True, max_length=3000, null=True)),
                ('po_qty', models.CharField(blank=True, max_length=3000, null=True)),
                ('bal_qty', models.CharField(blank=True, max_length=3000, null=True)),
                ('invoice_qty_nos', models.CharField(blank=True, max_length=3000, null=True)),
                ('invoice_qty_kg', models.CharField(blank=True, max_length=3000, null=True)),
                ('itemwt', models.CharField(blank=True, max_length=3000, null=True)),
                ('pkg_qty', models.CharField(blank=True, max_length=3000, null=True)),
                ('pkg_desc', models.CharField(blank=True, max_length=3000, null=True)),
                ('ref', models.CharField(blank=True, max_length=3000, null=True)),
                ('material_rate', models.CharField(blank=True, max_length=3000, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=3000, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Sales.gstjobworkinvoice')),
            ],
        ),
    ]
