# Generated by Django 5.2.8 on 2026-04-24 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0026_gstjobworkinvoice_gstjobworkgstdetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTJobworkRateDiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_note_no', models.CharField(blank=True, max_length=100, null=True)),
                ('debit_note_date', models.DateField(blank=True, null=True)),
                ('sub_total', models.CharField(blank=True, max_length=3000, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=3000, null=True)),
                ('cgst', models.CharField(blank=True, max_length=100, null=True)),
                ('sgst', models.CharField(blank=True, max_length=100, null=True)),
                ('igst', models.CharField(blank=True, max_length=100, null=True)),
                ('utgst', models.CharField(blank=True, max_length=100, null=True)),
                ('cgst_amt', models.DecimalField(blank=True, decimal_places=3, max_digits=50, null=True)),
                ('sgst_amt', models.DecimalField(blank=True, decimal_places=3, max_digits=50, null=True)),
                ('igst_amt', models.DecimalField(blank=True, decimal_places=3, max_digits=50, null=True)),
                ('utgst_amt', models.DecimalField(blank=True, decimal_places=3, max_digits=50, null=True)),
                ('grand_total', models.CharField(blank=True, max_length=3000, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('is_service_invoice', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GSTJobworkRatediffItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('inv_date', models.DateField(blank=True, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=3000, null=True)),
                ('qty', models.CharField(blank=True, max_length=3000, null=True)),
                ('old_rate', models.CharField(blank=True, max_length=3000, null=True)),
                ('new_rate', models.CharField(blank=True, max_length=3000, null=True)),
                ('diff', models.CharField(blank=True, max_length=3000, null=True)),
                ('diff_amt', models.CharField(blank=True, max_length=3000, null=True)),
                ('grir_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('grir_date', models.DateField(blank=True, null=True)),
                ('rate_diff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Sales.gstjobworkratediff')),
            ],
        ),
    ]
