# Generated by Django 5.2.8 on 2026-04-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0027_gstjobworkratediff_gstjobworkratediffitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstjobworkratediff',
            name='customer',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
