# Generated by Django 5.2.8 on 2026-04-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0028_gstjobworkratediff_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPoAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(blank=True, max_length=3000, null=True)),
                ('amd_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('amd_date', models.DateField(blank=True, null=True)),
                ('amd_type', models.CharField(blank=True, max_length=3000, null=True)),
                ('ref_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('ref_date', models.DateField(blank=True, null=True)),
                ('customer', models.CharField(blank=True, max_length=3000, null=True)),
                ('item_no', models.CharField(blank=True, max_length=3000, null=True)),
                ('item_code', models.CharField(blank=True, max_length=3000, null=True)),
                ('item_description', models.CharField(blank=True, max_length=3000, null=True)),
                ('new_rate', models.CharField(blank=True, max_length=3000, null=True)),
                ('new_qty', models.CharField(blank=True, max_length=3000, null=True)),
                ('eff_date', models.DateField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
