# Generated by Django 5.2.8 on 2026-04-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0029_customerpoamendment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpoamendment',
            name='old_qty',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='customerpoamendment',
            name='old_rate',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
