# Generated by Django 6.0.5 on 2026-05-26 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0030_customerpoamendment_old_qty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(blank=True, max_length=200, null=True)),
                ('series', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_type', models.CharField(blank=True, max_length=200, null=True)),
                ('credit_note_no', models.CharField(blank=True, max_length=200, null=True)),
                ('credit_note_date', models.DateField(blank=True, null=True)),
                ('party_name', models.CharField(blank=True, max_length=500, null=True)),
                ('supp_Crdr_no', models.CharField(blank=True, max_length=200, null=True)),
                ('supp_Crdr_date', models.DateField(blank=True, null=True)),
                ('inv_no', models.CharField(blank=True, max_length=200, null=True)),
                ('inv_date', models.DateField(blank=True, null=True)),
                ('select_gl', models.CharField(blank=True, max_length=200, null=True)),
                ('other_ref', models.CharField(blank=True, max_length=200, null=True)),
                ('for_e_invoice', models.CharField(blank=True, max_length=200, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('is_service_invoice', models.BooleanField(blank=True, default=False)),
                ('sub_total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('utgst', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('tcs', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cgst_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sgst_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('igst_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('urgst_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('tcs_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreadiNoteItemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_no', models.CharField(blank=True, max_length=200, null=True)),
                ('grn_date', models.DateField(blank=True, null=True)),
                ('item_code', models.CharField(blank=True, max_length=200, null=True)),
                ('item_no', models.CharField(blank=True, max_length=200, null=True)),
                ('item_description', models.CharField(blank=True, max_length=500, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=200, null=True)),
                ('rate', models.CharField(blank=True, max_length=200, null=True)),
                ('quntity', models.CharField(blank=True, max_length=200, null=True)),
                ('unit', models.CharField(blank=True, max_length=200, null=True)),
                ('ammount', models.CharField(blank=True, max_length=200, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Sales.creditnote')),
            ],
        ),
    ]
