# Generated by Django 6.0.5 on 2026-07-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0032_newprofomainvoice_newprofomainvoiceitemdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onwardchallan',
            name='DC_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onwardchallan',
            name='challan_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onwardchallan',
            name='challan_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onwardchallanitem',
            name='suppRefNo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='onwardchallanitem',
            name='wRate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='onwardchallanitem',
            name='wValue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
    ]
